apiVersion: v1
kind: ReplicationController
metadata: 
  name: hasher-rc
spec:
  replicas: 1
  selector: 
    app: hasher
    branch: istio
  template:
    metadata: 
      annotations:
        sidecar.istio.io/inject: 'true'
      labels: 
        app: hasher
        branch: istio
    spec: 
      containers:
        - 
          env: 
            - 
              name: author
              value: Ganimedes
          image: academiaonline/dockercoins:2.6-hasher
          # imagePullPolicy: Always
          name: hasher-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: phpinfo-rc
spec:
  replicas: 1
  selector: 
    app: phpinfo
    branch: istio
  template:
    metadata: 
      annotations:
        sidecar.istio.io/inject: 'true'
      labels: 
        app: phpinfo
        branch: istio
    spec: 
      containers:
        - 
          env: 
            - 
              name: author
              value: Ganimedes
          image: secobau/phpinfo:1.4
          # imagePullPolicy: Always
          name: phpinfo-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    service: phpinfo
  name: phpinfo
spec:
  clusterIP: ''
  ports: 
    - 
      name: http
      port: 8080
      protocol: TCP 
      targetPort: 8080
  selector:
    branch: istio
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: phpinfo
spec:
  host: phpinfo
  subsets:
    -
      name: hasher
      labels:
        app: hasher
    -
      name: phpinfo
      labels:
        app: phpinfo
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: phpinfo
spec:
  hosts:
    - '*'
  gateways:
    - phpinfo
  http:
    -
      match:
        -
          uri:
            exact: /phpinfo/
      route:
        -
          destination: 
            host: phpinfo
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: phpinfo
spec:
  selector:
    istio: ingressgateway
  servers:
    -
      port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - '*'
