apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: phpinfo
  name: phpinfo-po
spec:
  containers:
    - 
      args:
        - -f 
        - /src/index.php
        - -S
        - 0.0.0.0:8080
      command:
        - php
      env:
        -
          name: JAVA_HOME
          value: /var/lib/java
      image: php:apache
      name: phpinfo-container
      ports: 
        -
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
      workingDir: /src/
  volumes:
    - 
      configMap:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
---
apiVersion: v1
data:
  index.php: <?php phpinfo();?>
immutable: true
kind: ConfigMap
metadata: 
  name: phpinfo-cm
---
apiVersion: v1
kind: Service
metadata: 
  name: phpinfo-svc
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: phpinfo
  type: ClusterIP
