apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
  labels:
    app: phpinfo
    branch: santander
#  namespace: phpinfo
spec:
  containers:
    - 
      args:
        -  -f
        - src/index.php
        - -S
        - 0.0.0.0:8080
      command:
        - /usr/bin/php
      env:
        - 
          name: author
          value: Sergio
        -
          name: JAVA_HOME
          value: /var/lib/java
      name: phpinfo-container
      image: sergiosanz/phpinfo:santander
      ports:
        - 
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: /src/index.php
  volumes:
    -
      configMap:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
      # kubctl create cm --from-file ./src/index.php phpinfo-cm
 
