apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: phpinfo-template
objects:
  - 
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: phpinfo
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: phpinfo
      template:
        metadata:
          labels:
            app: phpinfo
        spec:
          containers:
          - name: phpinfo
            image: academiaonline/phpinfo:2.0
            imagePullPolicy: Always
            livenessProbe:
              tcpSocket:
                port: 8080
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            ports:
            - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              failureThreshold: 3
              initialDelaySeconds: 1
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
  - 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: phpinfo
    spec:
      podSelector:
        matchLabels:
          app: phpinfo
      ingress:
      - ports:
        - port: 8080
  - 
    apiVersion: v1
    kind: Service
    metadata:
      name: phpinfo
    spec:
      ports:
      - port: 80
        targetPort: 8080
      selector:
        app: phpinfo
      type: ClusterIP
  - 
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: phpinfo-route
    spec:
      to:
        kind: Service
        name: phpinfo
